---
apiVersion: v1
kind: Pod
metadata:
  name: greeter
spec:
  containers:
    - name: greeter
      image: rytis6lod/greeter-test
      ports:
        - containerPort: 8080
      livenessProbe:
          httpGet:
              path: /health
              port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: userdb
spec:
  containers:
    - name: userdb
      image: rytis6lod/userdb-test
      ports:
        - containerPort: 12679
      livenessProbe:
          httpGet:
              path: /demo/health
              port: 12679
          initialDelaySeconds: 10
          periodSeconds: 5
