---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: greeter-deployment
  labels:
    app: k8s-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-springboot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: k8s-springboot
        run: greeter
    spec:
      hostname: greeter
      containers:
      - name: greeter
        image: rytis6lod/greeter-test
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: userdb-deployment
  labels:
    app: k8s-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-springboot
        run: userdb
    spec:
      hostname: userdb
      containers:
      - name: userdb
        image: rytis6lod/userdb-test
        ports:
        - containerPort: 12679
        readinessProbe:
          httpGet:
            path: /demo/health
            port: 12679
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /demo/ping
            port: 12679
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: k8s-springboot
    run: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-springboot
    spec:
      hostname: config
      containers:
      - name: config
        image: rytis6lod/config-test
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
  labels:
    run: greeter
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: greeter
---
apiVersion: v1
kind: Service
metadata:
  name: userdb-service
  labels:
    run: userdb
spec:
  ports:
  - port: 12679
    protocol: TCP
  selector:
    run: userdb
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    run: config
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    run: config
