apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - port: 80
      name: web
    - port: 443
      name: https
    - port: 22
      name: ssh
  selector:
    app: gitlab
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      volumes:
        - name: "config"
          hostPath:
            path: "/srv/gitlab/config"
        - name: "logs"
          hostPath:
            path: "/srv/gitlab/logs"
        - name: "data"
#          persistentVolumeClaim:
#            claimName: mypvc
          azureDisk:
            diskName: kubernetes-dynamic-pvc-35babe83-1aaa-11e8-87b3-0a58ac1f09a5
            diskURI: "/subscriptions/d2b01e5b-40c2-4e21-b2e6-5f0a06324355/resourceGroups/MC_spark-k8s_test-kubernetes_centralus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-35babe83-1aaa-11e8-87b3-0a58ac1f09a5"
            kind: Managed
      containers:
      - image: gitlab/gitlab-ce:latest
        name: gitlab
        volumeMounts:
          - mountPath: "/etc/gitlab"
            name: "config"
          - mountPath: "/var/log/gitlab"
            name: "logs"
          - mountPath: "/var/opt/gitlab"
            name: "data"
        ports:
        - containerPort: 443
          name: https
        - containerPort: 80
          name: http
        - containerPort: 22
          name: ssh
