apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    app: spark
spec:
  ports:
    - port: 7077
      nodePort: 30077
      name: spark-master
    - port: 8080
      nodePort: 30080
      name: spark-ui
  selector:
    component: spark-master
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark-master
  labels:
    component: spark-master
spec:
  selector:
    matchLabels:
      component: spark-master
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
      - image: myspark
        name: spark-master
        env:
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: accesskey
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: secretkey
        ports:
        - containerPort: 7077
          name: spark
        - containerPort: 8080
          name: sparkui
        command: [ "/entrypoint.sh" ]
        args: ["/root/spark/bin/spark-class","org.apache.spark.deploy.master.Master"]
        imagePullPolicy: Never
