apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    component: spark-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      component: spark-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
      - image: gnut3ll4/ttauveron-spark:latest
        name: spark-worker
        ports:
        - containerPort: 8081
          name: spark
        - containerPort: 7078
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "1024Mi"
          limits:
            cpu: "200m"
            memory: "2048Mi"
        command: ["/start-worker.sh"]
