apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    component: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
      - image: gnut3ll4/ttauveron-spark
        name: spark-worker
        ports:
        - containerPort: 8081
          name: spark
        resources:
          requests:
            cpu: "150m"
            memory: "512Mi"
          limits:
            cpu: "150m"
            memory: "512Mi"
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark:7077"]
