apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spark
      tier: sparktier
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spark
        tier: sparktier
    spec:
      containers:
      - image: myspark
        name: spark-worker
        ports:
        - containerPort: 8081
          name: spark
        command: ["/root/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark:7077"]
        imagePullPolicy: Never
