apiVersion: v1
kind: Service
metadata:
  name: spark
  labels:
    app: spark
spec:
  ports:
    - port: 7077
  selector:
    app: spark
    tier: sparktier
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
spec:
  selector:
    matchLabels:
      app: spark
      tier: sparktier
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spark
        tier: sparktier
    spec:
      containers:
      - image: myspark
        name: myspark
        env:
        - name: MYSQL_DATABASE
          value: helloworld
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 7077
          name: spark
        command: [ "/entrypoint.sh" ]
        args: ["tail","-f","/dev/null"]
        imagePullPolicy: Never
