apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: azuredisk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
